### PR TITLE
closes #11 (multiple default media types)

### LINKED ISSUE #11: Allow multiple defined media types
https://github.com/raml-org/raml-spec/issues/234

### PR DESCRIPTION
**Pull request by petrochenko-pavel-a**

### CODE REVIEW

**Comment by petrochenko-pavel-a** [comment]
closes #11

**Comment by sichvoge** [comment]
Does that cover the value to be either a `string` or `sequence`?

**Comment by petrochenko-pavel-a** [comment]
yes. it covers.

**Comment by petrochenko-pavel-a** [comment]
merged into development branch

**Pull request closed without merging**
